language: python

python:
    - "2.7"
    - "3.3"

install:
    - python setup.py --quiet install

script:
    - rm -f .tmp
    - cppclean test/ | grep -v Processing | grep -v Unable | sort > .tmp
    - diff --unified .tmp test/expected.txt && rm -f .tmp
